M48
; DRILL file {KiCad (6.0.0-0)} date Wednesday, August 17, 2022 at 03:24:08 PM
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-08-17T15:24:08+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.0-0)
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.400
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C1.000
%
G90
G05
T1
X163.0Y-111.0
X165.4Y-110.8
X166.6Y-110.8
T2
X174.0Y-110.445
X174.0Y-112.985
X174.0Y-115.525
T0
M30
